### ISSUE TITLE
SRT323 not available as device to be added

### ISSUE THREAD

**Issue by oferinga** [priknr1/com.horstmann#3]
SRT323 is listed in the readme but not available as an option in the App (v0.1.3) when adding a device. 
See screenshot. SRT323 is not recognised when choosing the SRT321 option (closest matching).
How can I help to fix this?

<img width="699" alt="schermafbeelding 2017-10-22 om 01 39 02" src="https://user-images.githubusercontent.com/7810272/31856767-d02c5986-b6c9-11e7-80e9-742a2e2322d9.png">

**Comment by priknr1** [comment]
I will try to fix this today or tomorrow

**Comment by oferinga** [comment]
Super. If I can be of any help just let me know.

**Comment by priknr1** [comment]
I had a better look in my code. This device was never tested by someone. From what I can find in documentation online, it should have the same command classes as the SRT321.  The only difference should be the ID  for the SRT323 being 4, in stead of 3.

Therefor in theorie I should have been recognized as a SRT321.
Could you add the device for me with the Add device --> Homey --> Z-wave   
It should always add the device in homey, but might only show it as an on/off switch.   
When it is added, press the wrench, and go to Node Info.
I expect it to show
Manufacturer ID: 89
Product type ID: 1
Product ID: 4

Please let me know if this is correct, and if not, what values it does show.

**Comment by oferinga** [comment]
When I try to add it, Homey goes no further than 'Retrieving command class versions...' and then says 'No Z-Wave device has been found.' It is not listed as a device.
It does show up as an 'Unknown Z-Wave device' in the Network Graph under Settings.

From the log:
[2017-11-13T22:20:56.805Z] Command[6] start: addNode
[2017-11-13T22:20:56.829Z] Command[6] status: addNode, status: ADD_NODE_STATUS_LEARN_READY
[2017-11-13T22:20:59.964Z] Command[6] status: addNode, status: ADD_NODE_STATUS_NODE_FOUND
[2017-11-13T22:21:00.283Z] Command[6] status: addNode, status: ADD_NODE_STATUS_ADDING_SLAVE
[2017-11-13T22:21:00.449Z] Command[6] status: addNode, status: ADD_NODE_STATUS_PROTOCOL_DONE
[2017-11-13T22:21:00.503Z] Command[6] status: addNode, status: ADD_NODE_STATUS_DONE
[2017-11-13T22:21:00.705Z] Command[6] status: addNode, status: INTERVIEW_CC
[2017-11-13T22:21:00.710Z] Node[7]: sendData to COMMAND_CLASS_VERSION, params 0x1372
[2017-11-13T22:21:00.710Z] Command[7] start: sendData
[2017-11-13T22:21:00.713Z] ProcessSendData[6]: To node: 7 with data: 0x861372 and txOptions: ACK,AUTO_ROUTE,EXPLORE
[2017-11-13T22:21:00.738Z] Command[7] end: sendData
[2017-11-13T22:21:30.710Z] Command[6] end: addNode
[2017-11-13T22:22:43.044Z] Command[8] start: addNodeAbort
[2017-11-13T22:22:43.046Z] Command[8] end: addNodeAbort
[2017-11-13T22:22:52.076Z] Command[9] start: getNetworkTopology
[2017-11-13T22:22:52.076Z] Command[9] start: getNetworkTopology
[2017-11-13T22:22:52.114Z] Command[9] end: getNetworkTopology

**Comment by priknr1** [comment]
In that case, I think homey just loses connection while adding the device.
Try adding it again, maybe while holding the SRT323 closer.
It might take a couple of tries.

Did you have a look at the inclusion process?

https://forum.athom.com/discussion/comment/62230#Comment_62230

In your case, only the following steps should be sufficient:

9) Make sure the thermostat is still in installer mode (dip switch 1 On)
10) Turn the dial to ‘L’
11) Click "add device" in homey and select "Z-wave" under "Homey") 
12) Click the dial. 
13) Homey has now added the thermostat.

**Comment by priknr1** [comment]
Please let me know if you where able to get things working

**Comment by oferinga** [comment]
First try ended in a freeze of Homey. I measured the batteries and they were weak. I retried with a set of better batteries. No success. Adding procedure ends in saying no Z-Wave device was found but an 'Unknown device' was added. I placed the 323 right next to the Homey.

Will get a set of new batteries tomorrow and try again.

**Comment by priknr1** [comment]
I know my SRT321 does not work properly on rechargable battery's (they only supply 1.5 V in stead of 1.8 for a normal battery.)

**Comment by oferinga** [comment]
Didn't manage to pick up new batteries today. Will do tomorrow.

**Comment by oferinga** [comment]
With a set of brand new batteries it still does not work out. Is there a way to get more verbose logging for you out of Homey?

**Comment by priknr1** [comment]
In the appstore there is a logger, maybe you can do something with that.
But I dont think it will help you much. The device should at least be added in your device list (not the zwave overview, actually as a device in the zone/room where you have pressed the "+ " sign.

Even if you dont have the Secure/Horstmann app at all, it would always ad it as a general z-wave device. So i dont think there is anything I can change in my app code to make it work.
It might be best to join slack (homey development chat) slack.athom.com  And ask TedTolboom or Caseda Or RobinBolscher there, They are zwave experts
