### ISSUE TITLE
SRT321: not able to change temperature when connected to boiler switch.

### ISSUE THREAD

**Issue by Mecallie** [priknr1/com.horstmann#5]
I have an SRT 321 that I paired with Homey. I can update the set temperature via Homey on the thermostat. However, as soon as I link the thermostat to a boiler switch as well I can no longer update the temperature on the thermostat. The readouts still work, but when I change the temperature through Homey I get a time-out.

As soon as I unlink it and add-it again to Homey I can set the temperature just fine.

I would like to be able to change the set temperature on the thermostat whilst it is connected to the boiler switch,

**Comment by priknr1** [comment]
@Mecallie 
Sorry for my late response.
I get the timeout failure as well.

But if you look at your thermostat 5 minutes later (assuming your wake-up time is 5 minutes)  the target temperature has update.

So you get a message, but it works anyway.
