### ISSUE TITLE
Unclear how to get SES303 added with 4 SES002

### ISSUE THREAD

**Issue by DomoHans** [priknr1/com.horstmann#6]
I have repeatedly removed the SES303 from z-wave, connected SES002 to SES303, and pressed the button until led flashes. SES303 gets added but not a single SES002. Some more guidance would be helpful.

**Comment by priknr1** [comment]
I dont own the devices, I added them from info found on the internet, maybe it is best to try it at the forum:

Someone might read it and be able to help you.

[https://community.athom.com/t/secure-horstmann-app/8693/2
](https://community.athom.com/t/secure-horstmann-app/8693/2
)
