### ISSUE TITLE
Horstman SRT321 is only recognized as a Basic Z-Wave device

### ISSUE THREAD

**Issue by tooxe** [priknr1/com.horstmann#7]
SRT321 is listed in the read me in App Store 2 as available device. After when it has been installed SRT321 is not recognized and stated as Basic Z-Wave device.
During the installation it is retrieving command class versions etc. I have tried include and exclude several times and even holding the SRT321 very close …

I have got advice to contact you and ask if you possible could make following changes in you application:
The SRT321 in the app is defined with a productID of 3, while my device is reporting 5. That explains the inability to find a match during inclusion.

I hope you can help me :-)
Please read the conversation [here](https://community.athom.com/t/horstman-srt321-is-only-recognized-as-a-basic-z-wave-device/6283/9)
Tomas from Sweden

**Comment by priknr1** [comment]
Sorry for my late response,

I uploaded a new version to the appstore, it should b available soon.
Please re-add the device with the new version. Let me know if things are working for you now.
