### ISSUE TITLE
homey 2.0 compatibility

### ISSUE THREAD

**Issue by daesland** [priknr1/com.horstmann#8]
Hi, can anyone confirm if this app works with homey v2.0.
I have about 15 secure/horstmann/iqe thermostats that work great and will be a very expensive nightmare if they do not work with version 2.0 and I can't go back to the previous working version. 
Any help appreciated, I can't find anything on the athom forum that confirms either way.

**Comment by priknr1** [comment]
@daesland  I have received messages from 2 people that the app is working in Homey V2.0
