### ISSUE TITLE
Horstmann SRT321 is not shown anymore in Homey 1.5.13 after app updated to v0.1.5 - 22.01.19

### ISSUE THREAD

**Issue by pln8421** [priknr1/com.horstmann#9]
Hello,

I have a copuple of SRT321 and realized they not shown live in Homey.
Went into appstore and saw there was an update to v0.1.5,  8 days ago.
Nothing written in changelog.
They are still working towards relays but I'm blind and Homey not able to send an alarm if temperature goes down towards 0.

**Comment by priknr1** [comment]
The V1.5 has only add one device type ID, I have the SRT321 myself, still working fine. So a pull-the-plug or refresh of the app should just do the trick.
